version: "3.7"

services:
  app:
    build: app
    image: akhng999/django-gunicorn-vn
#    container_name: django-gunicorn
#    restart: always
    expose:
      - "8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 taskManager.wsgi:application"

  nginx:
    build: nginx
    image: akhng999/nginx:ngx_appprotect
    container_name: ngx_appprotect
    ports:
      - "80:80"
    volumes:
    #  - ./nginx/:/etc/nginx/conf.d
      - ./nginx/app_protect/:/etc/app_protect/conf
    depends_on:
      - app
